import { NextResponse } from "next/server.js";
import { cookies } from "next/headers.js";
import { createServerSupabaseClient } from "../../../../lib/supabase/server.js";
import { createAdminSupabaseClient } from "../../../../lib/supabase/admin.js";
import { isAdminEmail } from "../../../../lib/supabase/admin-access.js";

const errorResponse = (error, status) => NextResponse.json({ error }, { status });
const isUniqueViolation = (error) => error?.code === "23505";
const SELECT_FIELDS = "id,slug,collection_type,title,title_zh,intro,intro_zh,date_range,location,location_zh,cover_photo_id,published,created_at,updated_at";
async function clients(options = {}) { const userClient = options.userClient || createServerSupabaseClient(await cookies()); const { data, error } = await userClient.auth.getUser(); if (error || !data?.user) return { response: errorResponse("Unauthorized", 401) }; if (!isAdminEmail(data.user.email)) return { response: errorResponse("Admin access is not configured", 403) }; return { adminClient: options.adminClient || createAdminSupabaseClient() }; }
const fields = ["slug", "collection_type", "title", "title_zh", "intro", "intro_zh", "date_range", "location", "location_zh", "cover_photo_id", "published"];
function validate(input, partial = false) { const update = Object.fromEntries(fields.filter((key) => Object.hasOwn(input || {}, key)).map((key) => [key, input[key]])); if (!partial && (!update.slug || !update.collection_type || !update.title)) throw new Error("Missing required collection fields"); if (update.collection_type && !["theme", "workshop"].includes(update.collection_type)) throw new Error("Invalid collection_type"); if (update.published !== undefined && typeof update.published !== "boolean") throw new Error("Invalid published"); for (const key of ["slug", "title", "title_zh", "intro", "intro_zh", "date_range", "location", "location_zh", "cover_photo_id"]) if (update[key] !== undefined && (typeof update[key] !== "string" || update[key].length > 500 || (["slug", "title"].includes(key) && !update[key].trim()))) throw new Error(`Invalid ${key}`); return update; }
export async function getHandler(request, options = {}) { try { const ready = await clients(options); if (ready.response) return ready.response; const type = new URL(request.url).searchParams.get("type"); if (type && !["theme", "workshop"].includes(type)) return errorResponse("Invalid collection type", 400); let query = ready.adminClient.from("photo_collections").select(SELECT_FIELDS).order("created_at", { ascending: false }); if (type) query = query.eq("collection_type", type); const result = await query; if (result.error) return errorResponse("Failed to load collections", 500); return NextResponse.json({ collections: result.data || [] }); } catch { return errorResponse("Failed to load collections", 500); } }
export async function postHandler(request, options = {}) { try { const ready = await clients(options); if (ready.response) return ready.response; const input = validate(await request.json()); const result = await ready.adminClient.from("photo_collections").insert(input).select(SELECT_FIELDS).single(); if (result.error) return isUniqueViolation(result.error) ? errorResponse("Collection slug already exists", 409) : errorResponse("Failed to create collection", 500); return NextResponse.json({ collection: result.data }, { status: 201 }); } catch (error) { return errorResponse(error.message || "Invalid request", 400); } }
export async function GET(request, options) { return getHandler(request, options); }
export async function POST(request, options) { return postHandler(request, options); }
