export const additionalPhotos = [
  {
    "id": "landscape-0534585e-c520-405e-821d-49b914999083",
    "src": "/photos/themes/landscape/0534585e-c520-405e-821d-49b914999083.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-0744de76-2766-4a94-8ba8-425a80c4954b",
    "src": "/photos/themes/landscape/0744de76-2766-4a94-8ba8-425a80c4954b.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-0e921de3-fe69-405e-a0be-3f7d8ae37dfe",
    "src": "/photos/themes/landscape/0e921de3-fe69-405e-a0be-3f7d8ae37dfe.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-3b0b64eb-8b9c-403c-9c84-343c21cf79bc",
    "src": "/photos/themes/landscape/3b0b64eb-8b9c-403c-9c84-343c21cf79bc.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-43884500-198d-44b4-bac0-e146754ef8aa",
    "src": "/photos/themes/landscape/43884500-198d-44b4-bac0-e146754ef8aa.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-45647a41-1395-403d-a552-13fdb1a0a813",
    "src": "/photos/themes/landscape/45647a41-1395-403d-a552-13fdb1a0a813.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-5b89274f-ef29-4038-a24f-85b229cc27ee",
    "src": "/photos/themes/landscape/5b89274f-ef29-4038-a24f-85b229cc27ee.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-63cece03-b176-4016-88fa-ea4231fca385",
    "src": "/photos/themes/landscape/63cece03-b176-4016-88fa-ea4231fca385.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-b4c97c4c-423e-45bf-ba2f-b0d6ece1d553",
    "src": "/photos/themes/landscape/b4c97c4c-423e-45bf-ba2f-b0d6ece1d553.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-c1843fa9-b50c-4bcd-a770-93e5b91edb59",
    "src": "/photos/themes/landscape/c1843fa9-b50c-4bcd-a770-93e5b91edb59.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-c30ddbda-91bc-40f8-b1d9-e941a86826fc",
    "src": "/photos/themes/landscape/c30ddbda-91bc-40f8-b1d9-e941a86826fc.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-e7c7d3b7-bedd-499d-b287-f96ee8ed0dc6",
    "src": "/photos/themes/landscape/e7c7d3b7-bedd-499d-b287-f96ee8ed0dc6.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-fine-img-2",
    "src": "/photos/themes/landscape/fine-img-2.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-11",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-fine-img",
    "src": "/photos/themes/landscape/fine-img.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-10",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-1703",
    "src": "/photos/themes/landscape/img-1703.webp",
    "alt": "Landscape photograph",
    "date": "2026-06-27",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20230801-0099",
    "src": "/photos/themes/landscape/img-20230801-0099.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-01",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20230801-0162",
    "src": "/photos/themes/landscape/img-20230801-0162.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-01",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20230804-0002",
    "src": "/photos/themes/landscape/img-20230804-0002.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-04",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20231119-0006",
    "src": "/photos/themes/landscape/img-20231119-0006.webp",
    "alt": "Landscape photograph",
    "date": "2023-11-19",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20240715-0002",
    "src": "/photos/themes/landscape/img-20240715-0002.webp",
    "alt": "Landscape photograph",
    "date": "2024-07-15",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20240715-0015",
    "src": "/photos/themes/landscape/img-20240715-0015.webp",
    "alt": "Landscape photograph",
    "date": "2024-07-15",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-3200",
    "src": "/photos/themes/landscape/img-3200.webp",
    "alt": "Landscape photograph",
    "date": "2026-08-11",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-3209",
    "src": "/photos/themes/landscape/img-3209.webp",
    "alt": "Landscape photograph",
    "date": "2026-08-11",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-3210",
    "src": "/photos/themes/landscape/img-3210.webp",
    "alt": "Landscape photograph",
    "date": "2026-08-11",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "people-2733-livephoto",
    "src": "/photos/themes/people/2733-livephoto.webp",
    "alt": "People photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-1507",
    "src": "/photos/themes/people/img-1507.webp",
    "alt": "People photograph",
    "date": "2026-06-22",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-1982",
    "src": "/photos/themes/people/img-1982.webp",
    "alt": "People photograph",
    "date": "2026-07-01",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-20231003-0062",
    "src": "/photos/themes/people/img-20231003-0062.webp",
    "alt": "People photograph",
    "date": "2023-10-03",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-2373",
    "src": "/photos/themes/people/img-2373.webp",
    "alt": "People photograph",
    "date": "2026-07-06",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-2505",
    "src": "/photos/themes/people/img-2505.webp",
    "alt": "People photograph",
    "date": "2026-07-06",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-2669",
    "src": "/photos/themes/people/img-2669.webp",
    "alt": "People photograph",
    "date": "2026-07-11",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-6997",
    "src": "/photos/themes/people/img-6997.webp",
    "alt": "People photograph",
    "date": "2024-11-23",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-8292",
    "src": "/photos/themes/people/img-8292.webp",
    "alt": "People photograph",
    "date": "2025-08-25",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-8294",
    "src": "/photos/themes/people/img-8294.webp",
    "alt": "People photograph",
    "date": "2025-08-25",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-uusce1082",
    "src": "/photos/themes/people/uusce1082.webp",
    "alt": "People photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "food-bgzye1024",
    "src": "/photos/themes/food/bgzye1024.webp",
    "alt": "Food photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-dyuie8604",
    "src": "/photos/themes/food/dyuie8604.webp",
    "alt": "Food photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-img-20230806-0028",
    "src": "/photos/themes/food/img-20230806-0028.webp",
    "alt": "Food photograph",
    "date": "2023-08-06",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-img-20230909-0006",
    "src": "/photos/themes/food/img-20230909-0006.webp",
    "alt": "Food photograph",
    "date": "2023-09-09",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-img-20230909-0016",
    "src": "/photos/themes/food/img-20230909-0016.webp",
    "alt": "Food photograph",
    "date": "2023-09-09",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  }
];
