export const additionalPhotos = [
  {
    "id": "landscape-0534585e-c520-405e-821d-49b914999083",
    "src": "/photos/themes/landscape/0534585e-c520-405e-821d-49b914999083.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Zhuhai, Guangdong, China",
    "locationZh": "中国 珠海市",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-0744de76-2766-4a94-8ba8-425a80c4954b",
    "src": "/photos/themes/landscape/0744de76-2766-4a94-8ba8-425a80c4954b.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "School of Music, The Chinese University of Hong Kong, Shenzhen",
    "locationZh": "中国 广东省 深圳市 龙岗区 香港中文大学（深圳）音乐学院",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-0e921de3-fe69-405e-a0be-3f7d8ae37dfe",
    "src": "/photos/themes/landscape/0e921de3-fe69-405e-a0be-3f7d8ae37dfe.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-3b0b64eb-8b9c-403c-9c84-343c21cf79bc",
    "src": "/photos/themes/landscape/3b0b64eb-8b9c-403c-9c84-343c21cf79bc.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Zhuhai, Guangdong, China",
    "locationZh": "中国 珠海市",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-43884500-198d-44b4-bac0-e146754ef8aa",
    "src": "/photos/themes/landscape/43884500-198d-44b4-bac0-e146754ef8aa.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Zhuhai, Guangdong, China",
    "locationZh": "中国 珠海市",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-45647a41-1395-403d-a552-13fdb1a0a813",
    "src": "/photos/themes/landscape/45647a41-1395-403d-a552-13fdb1a0a813.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-5b89274f-ef29-4038-a24f-85b229cc27ee",
    "src": "/photos/themes/landscape/5b89274f-ef29-4038-a24f-85b229cc27ee.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "The Chinese University of Hong Kong, Shenzhen",
    "locationZh": "中国 广东省 深圳市 龙岗区 香港中文大学（深圳）",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-63cece03-b176-4016-88fa-ea4231fca385",
    "src": "/photos/themes/landscape/63cece03-b176-4016-88fa-ea4231fca385.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Wukang Road, Shanghai, China",
    "locationZh": "中国 上海市 武康路",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-b4c97c4c-423e-45bf-ba2f-b0d6ece1d553",
    "src": "/photos/themes/landscape/b4c97c4c-423e-45bf-ba2f-b0d6ece1d553.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Zhuhai, Guangdong, China",
    "locationZh": "中国 珠海市",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-c1843fa9-b50c-4bcd-a770-93e5b91edb59",
    "src": "/photos/themes/landscape/c1843fa9-b50c-4bcd-a770-93e5b91edb59.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "The Chinese University of Hong Kong, Shenzhen",
    "locationZh": "中国 广东省 深圳市 龙岗区 香港中文大学（深圳）",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-c30ddbda-91bc-40f8-b1d9-e941a86826fc",
    "src": "/photos/themes/landscape/c30ddbda-91bc-40f8-b1d9-e941a86826fc.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Foshan, Guangdong, China",
    "locationZh": "中国 广东省 佛山市",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-e7c7d3b7-bedd-499d-b287-f96ee8ed0dc6",
    "src": "/photos/themes/landscape/e7c7d3b7-bedd-499d-b287-f96ee8ed0dc6.webp",
    "alt": "Landscape photograph",
    "date": "",
    "location": "Yayi Park, Chancheng District, Foshan, Guangdong, China",
    "locationZh": "中国 广东省 佛山市 禅城区 亚艺公园",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-fine-img-2",
    "src": "/photos/themes/landscape/fine-img-2.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-11",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-fine-img",
    "src": "/photos/themes/landscape/fine-img.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-10",
    "location": "Putuo District, Zhoushan, Zhejiang, China",
    "locationZh": "中国 浙江省 舟山市 普陀区",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-1703",
    "src": "/photos/themes/landscape/img-1703.webp",
    "alt": "Landscape photograph",
    "date": "2026-06-27",
    "location": "Unity Pavilion, The Chinese University of Hong Kong",
    "locationZh": "中国 香港 香港中文大学 天人合一",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20230801-0099",
    "src": "/photos/themes/landscape/img-20230801-0099.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-01",
    "location": "Shanghai, China",
    "locationZh": "中国 上海市",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20230801-0162",
    "src": "/photos/themes/landscape/img-20230801-0162.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-01",
    "location": "Xiamen, Fujian, China",
    "locationZh": "中国 厦门",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20230804-0002",
    "src": "/photos/themes/landscape/img-20230804-0002.webp",
    "alt": "Landscape photograph",
    "date": "2023-08-04",
    "location": "Shanghai, China",
    "locationZh": "中国 上海",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20231119-0006",
    "src": "/photos/themes/landscape/img-20231119-0006.webp",
    "alt": "Landscape photograph",
    "date": "2023-11-19",
    "location": "Yayi Park, Chancheng District, Foshan, Guangdong, China",
    "locationZh": "中国 广东省 禅城区 亚艺公园",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20240715-0002",
    "src": "/photos/themes/landscape/img-20240715-0002.webp",
    "alt": "Landscape photograph",
    "date": "2024-07-15",
    "location": "Xiamen, Fujian, China",
    "locationZh": "中国 厦门",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-20240715-0015",
    "src": "/photos/themes/landscape/img-20240715-0015.webp",
    "alt": "Landscape photograph",
    "date": "2024-07-15",
    "location": "Xiamen, Fujian, China",
    "locationZh": "中国 厦门",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-3200",
    "src": "/photos/themes/landscape/img-3200.webp",
    "alt": "Landscape photograph",
    "date": "2026-08-11",
    "location": "Akanara Beach, Shenzhen, Guangdong, China",
    "locationZh": "中国 广东省 深圳市 龙岗区 阿卡那拉海滩",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-3209",
    "src": "/photos/themes/landscape/img-3209.webp",
    "alt": "Landscape photograph",
    "date": "2026-08-11",
    "location": "Akanara Beach, Shenzhen, Guangdong, China",
    "locationZh": "中国 广东省 深圳市 龙岗区 阿卡那拉海滩",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "landscape-img-3210",
    "src": "/photos/themes/landscape/img-3210.webp",
    "alt": "Landscape photograph",
    "date": "2026-08-11",
    "location": "Akanara Beach, Shenzhen, Guangdong, China",
    "locationZh": "中国 广东省 深圳市 龙岗区 阿卡那拉海滩",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "landscape"
  },
  {
    "id": "people-2733-livephoto",
    "src": "/photos/themes/people/2733-livephoto.webp",
    "alt": "People photograph",
    "date": "",
    "location": "Sheung Wan, Hong Kong",
    "locationZh": "中国 香港 上环",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-1507",
    "src": "/photos/themes/people/img-1507.webp",
    "alt": "People photograph",
    "date": "2026-06-22",
    "location": "Central, Hong Kong",
    "locationZh": "中国 香港 中环",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-1982",
    "src": "/photos/themes/people/img-1982.webp",
    "alt": "People photograph",
    "date": "2026-07-01",
    "location": "Sheung Wan, Hong Kong",
    "locationZh": "中国 香港 上环",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-20231003-0062",
    "src": "/photos/themes/people/img-20231003-0062.webp",
    "alt": "People photograph",
    "date": "2023-10-03",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-2373",
    "src": "/photos/themes/people/img-2373.webp",
    "alt": "People photograph",
    "date": "2026-07-06",
    "location": "Ocean Park, Hong Kong",
    "locationZh": "中国 香港 海洋公园",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-2505",
    "src": "/photos/themes/people/img-2505.webp",
    "alt": "People photograph",
    "date": "2026-07-06",
    "location": "Ocean Park, Hong Kong",
    "locationZh": "中国 香港 海洋公园",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-2669",
    "src": "/photos/themes/people/img-2669.webp",
    "alt": "People photograph",
    "date": "2026-07-11",
    "location": "MacLehose Trail, Hong Kong",
    "locationZh": "中国 香港 麦理浩径",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-6997",
    "src": "/photos/themes/people/img-6997.webp",
    "alt": "People photograph",
    "date": "2024-11-23",
    "location": "EXP Study Space, Chancheng District, Foshan, Guangdong, China",
    "locationZh": "中国 广东省 禅城区 EXP学习空间",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-8292",
    "src": "/photos/themes/people/img-8292.webp",
    "alt": "People photograph",
    "date": "2025-08-25",
    "location": "Library, The Chinese University of Hong Kong, Shenzhen",
    "locationZh": "中国 广东省 深圳市 龙岗区 香港中文大学（深圳）图书馆",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-img-8294",
    "src": "/photos/themes/people/img-8294.webp",
    "alt": "People photograph",
    "date": "2025-08-25",
    "location": "Library, The Chinese University of Hong Kong, Shenzhen",
    "locationZh": "中国 广东省 深圳市 龙岗区 香港中文大学（深圳）图书馆",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "people-uusce1082",
    "src": "/photos/themes/people/uusce1082.webp",
    "alt": "People photograph",
    "date": "",
    "location": "EXP Study Space, Chancheng District, Foshan, Guangdong, China",
    "locationZh": "中国 广东省 禅城区 EXP学习空间",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "people"
  },
  {
    "id": "food-bgzye1024",
    "src": "/photos/themes/food/bgzye1024.webp",
    "alt": "Food photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-dyuie8604",
    "src": "/photos/themes/food/dyuie8604.webp",
    "alt": "Food photograph",
    "date": "",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-img-20230806-0028",
    "src": "/photos/themes/food/img-20230806-0028.webp",
    "alt": "Food photograph",
    "date": "2023-08-06",
    "location": "",
    "locationZh": "中国 ",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-img-20230909-0006",
    "src": "/photos/themes/food/img-20230909-0006.webp",
    "alt": "Food photograph",
    "date": "2023-09-09",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  },
  {
    "id": "food-img-20230909-0016",
    "src": "/photos/themes/food/img-20230909-0016.webp",
    "alt": "Food photograph",
    "date": "2023-09-09",
    "location": "",
    "locationZh": "",
    "note": "",
    "noteZh": "",
    "aspect": "landscape",
    "collectionType": "themes",
    "collectionSlug": "food"
  }
];
