import { NextResponse } from "next/server.js";
import { cookies } from "next/headers.js";
import { createServerSupabaseClient } from "../../../../../lib/supabase/server.js";
import { createAdminSupabaseClient } from "../../../../../lib/supabase/admin.js";
import { isAdminEmail } from "../../../../../lib/supabase/admin-access.js";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const errorResponse = (error, status) => NextResponse.json({ error }, { status });
const isUniqueViolation = (error) => error?.code === "23505";
const SELECT_FIELDS = "id,slug,collection_type,title,title_zh,intro,intro_zh,date_range,location,location_zh,cover_photo_id,published,created_at,updated_at";
async function clients(options = {}) { const userClient = options.userClient || createServerSupabaseClient(await cookies()); const { data, error } = await userClient.auth.getUser(); if (error || !data?.user) return { response: errorResponse("Unauthorized", 401) }; if (!isAdminEmail(data.user.email)) return { response: errorResponse("Admin access is not configured", 403) }; return { adminClient: options.adminClient || createAdminSupabaseClient() }; }
const fields = ["slug", "collection_type", "title", "title_zh", "intro", "intro_zh", "date_range", "location", "location_zh", "cover_photo_id", "published"];
export async function patchHandler(request, { params, ...options } = {}) { try { const ready = await clients(options); if (ready.response) return ready.response; const id = (await params).id; if (!UUID.test(id)) return errorResponse("Invalid collection id", 400); const input = await request.json(); const update = Object.fromEntries(fields.filter((key) => Object.hasOwn(input || {}, key)).map((key) => [key, input[key]])); if (update.collection_type && !["theme", "workshop"].includes(update.collection_type)) return errorResponse("Invalid collection_type", 400); if (update.published !== undefined && typeof update.published !== "boolean") return errorResponse("Invalid published", 400); for (const key of ["slug", "title", "title_zh", "intro", "intro_zh", "date_range", "location", "location_zh", "cover_photo_id"]) if (update[key] !== undefined && (typeof update[key] !== "string" || update[key].length > 500 || (["slug", "title"].includes(key) && !update[key].trim()))) return errorResponse(`Invalid ${key}`, 400); if (!Object.keys(update).length) return errorResponse("No editable fields supplied", 400); const lookup = ready.adminClient.from("photo_collections"); if (typeof lookup.select === "function") { const existing = await lookup.select("collection_type").eq("id", id).single(); if (existing.error || !existing.data) return errorResponse("Collection not found", 404); if (update.collection_type && update.collection_type !== existing.data.collection_type) return errorResponse("Collection type cannot be changed", 400); } const chain = ready.adminClient.from("photo_collections").update(update).eq("id", id); const result = chain.select ? await chain.select(SELECT_FIELDS).single() : await chain; if (result.error) return isUniqueViolation(result.error) ? errorResponse("Collection slug already exists", 409) : errorResponse("Failed to update collection", 500); if (!result.data) return errorResponse("Collection not found", 404); return NextResponse.json({ collection: result.data }); } catch { return errorResponse("Invalid request", 400); } }
export async function deleteHandler(request, { params, ...options } = {}) { try { const ready = await clients(options); if (ready.response) return ready.response; const id = (await params).id; if (!UUID.test(id)) return errorResponse("Invalid collection id", 400); if (new URL(request.url).searchParams.get("confirm") !== "true") return errorResponse("Explicit confirmation is required", 400); const lookup = ready.adminClient.from("photo_collections").select("id").eq("id", id); const found = typeof lookup.single === "function" ? await lookup.single() : { data: { id }, error: null }; if (found.error) return errorResponse("Collection not found", found.error.code === "PGRST116" ? 404 : 500); if (!found.data) return errorResponse("Collection not found", 404); const result = await ready.adminClient.from("photo_collections").delete().eq("id", id); if (result.error) return errorResponse("Failed to delete collection", 500); return NextResponse.json({ deleted: true }); } catch { return errorResponse("Failed to delete collection", 500); } }
export async function PATCH(request, context) { return patchHandler(request, context); }
export async function DELETE(request, context) { return deleteHandler(request, context); }
